/*
    Master UI Resource File
*/

#include "common.hpp"
#include "defines.hpp"
#include "ada_telefono.hpp"
#include "shop_items.hpp"
#include "player_inv.hpp"
#include "gang.hpp"
#include "key_chain.hpp"
#include "impound.hpp"
#include "bank.hpp"
#include "veh_shop.hpp"
#include "shops.hpp"
#include "Colores.hpp"
//#include "hud_stats.hpp"
#include "admin_menu.hpp"
#include "cell_phone.hpp"
#include "wanted_list.hpp"
#include "ticket.hpp"
#include "clothing.hpp"
#include "trunk.hpp"
#include "spawnSelection.hpp"
#include "chop_shop.hpp"
#include "pInteraction.hpp"
#include "deathScreen.hpp"
#include "vehicleShop.hpp"
#include "vehicleShop3D.hpp"
#include "settings.hpp"
#include "federalReserve.hpp"
#include "compensate.hpp"
#include "FuelStat.hpp"
#include "newsStation.hpp"
#include "AKRMasterClass.hpp"

//AxE

#include "HUDica.hpp"
#include "Debug.hpp"
#include "craft.hpp"
#include "menuY.hpp"
#include "menubaile.hpp"
#include "barrita.hpp"
#include "menuCompraVenta.hpp"
#include "taximenu.hpp"
#include "explosivePad.hpp"
#include "spmenu.hpp"
#include "bbmenu.hpp"
#include "pandemia.hpp"
#include "group.hpp"
#include "eventojuan.hpp"
#include "tiendaPoli.hpp"
#include "tiendaTerro.hpp"
#include "bancobandas.hpp"
#include "tiendaBf.hpp"
#include "blackjack.hpp"
#include "roulette.hpp"
#include "chapas_dialog.h"
#include "gasolinera2.hpp"
#include "taller.hpp"
#include "sp_dialog.h"
#include "menuzonas.hpp"
#include "mafia_casa.hpp"
#include "tienda.hpp"
#include "tienda_vacia.hpp"
#include "carnetabogado.hpp"
#include "granjapop.hpp"
class dsl_Slider : axe_RscSlider
{
}; 
#include "resincl.hpp"
#include "tiendaPol.hpp"
#include "experiencia.hpp"
#include "axeTrans.hpp"
#include "portatilhw.hpp"
#include "papelhhw.hpp"
#include "tablet.hpp"
#include "portatil.hpp"
#include "arrestmenu.hpp"
#include "veh_repaint.hpp"
#include "channel.hpp"
#include "centralica.hpp"
#include "centralaxe.hpp"


// farmeos
#include "pesca.hpp"
#include "mineria.hpp"
#include "llenandoBotella.hpp"
#include "buscandoPetroleo.hpp"
#include "picando.hpp"

// cosasrandom
#include "menutrol.hpp"
#include "wikipedia.hpp"

// robos y mafia
#include "topsecret.hpp"
#include "hacker.hpp"
#include "ganzua.hpp"
#include "traficante.hpp"
#include "tiendaMafia.hpp"

// economia
#include "loteria.hpp"
#include "gasolinera.hpp"
#include "subastas.hpp"
#include "sacoDineroPublico.hpp"
#include "transportes.hpp"

// policia
#include "policia.hpp"
#include "camaras.hpp"
#include "cacheo.hpp"

#include "daDinero.hpp"
#include "daLlaves.hpp"
#include "mensajesica.hpp"
#include "centralita.hpp"

//Rosen
#include "tragaperras.hpp"
#include "inscripcion.hpp"
#include "votar.hpp"
#include "tallerRosen.hpp"
#include "carrera_ilegal.hpp"
#include "apuesta_diag.hpp"
#include "mercarosen.hpp"
#include "hintr.hpp"
#include "cine.hpp"
#include "bailes.hpp"