        if (("ter" call ica_fnc_expToLevel) < 7) exitWith {
            titleText["No sabes como van estos contactos ni estos negocios ...", "PLAIN"];
    };
if (zona_6 getVariable "codigo" != life_gangzona) exitWith {hint "Solo los que controlan la zona del Barrio Arabe pueden Contactar conmigo ... ya sabes, por mi propia seguridad."};	
_posPlayer = getPos player;
if !({side _x == WEST} count playableUnits >= 18) exitWith {hint "Tienen que estar al menos 18 policias conectados, sino, no es divertido."};
if (!paqueteaereo_enable) exitWith {hint "ELN: No has demostrado tu valía sembrando el terror como para enviarte suministros..."};
if (paqueteaereo_goingon) exitWith {hint "ELN: Ya hemos enviado un cargamento de suministros..."};
paqueteaereo_goingon = true;
paqueteaereo_enable = false;
publicVariable "paqueteaereo_enable";
paqueteaereo_helicoptero_main = "B_Heli_Transport_03_unarmed_F";
_dest = _posPlayer;
_liderterro = name player;
_pic1 = ["Cha_AKS74U"] call ica_fnc_classToPic;
hintSilent parseText format["<img image='%1' size='1.50'/><t size='1' align ='center' color='#ffffff' shadow='2' font='EtelkaNarrowMediumPro'>ELN: </t><br/><t size='0.80' align ='center' color='#ffffff' font='EtelkaMonospacePro'><br/> Hola %2 ... Tus acciones hablan por ti y nos has probado que tus ideales los haces respetar queremos entonces apoyar tu lucha ...  <br/>te enviaremos suministros desde el aire que equiparen con las fuerzas del estado corrupto al que enfrentas.</t>",_pic1, _liderterro];
sleep 1;
_message = "Atención a todos los ciudadanos, es posible que el ELN envie suministros a sus militantes en la isla, les pedimos reportar a la policia cualquier anomalía y alejarse de la zona puede ser peligroso.";
[[10, "Aviso", [1,0,0], 1.5, _message, [1,1,1], 1], "ica_fnc_anuncio", nil, false, false] call life_fnc_MP;
sleep 30;
_markerText = createMarker ["Markerpaquetetext", _dest];
"Markerpaquetetext" setMarkerColor "ColorBlack";
"Markerpaquetetext" setMarkerText "Destino de Entrega ELN";
"Markerpaquetetext" setMarkerType "mil_warning";
heli1 = CreateVehicle [paqueteaereo_helicoptero_main, [7950, 9667, 0], [], 0, "FLY"];
heli1 allowDamage false;
_mygroup1 = [[7950, 9667, 0], CIVILIAN, ["O_G_Soldier_SL_F"],[],[],[],[],[],180] call BIS_fnc_spawnGroup;
{_x moveInDriver heli1} forEach units _mygroup1;
_mygroup1 addWaypoint [_dest, 0];
_mygroup1 addWaypoint [[2380.47,22267.8,0], 0];
_markerText = createMarker ["marcador_paquete", [14028.5,18719.7,0.0014267]];
"marcador_paquete" setMarkerColor "ColorBlue";
"marcador_paquete" setMarkerText "Helicoptero no identificado";
"marcador_paquete" setMarkerType "mil_destroy";
_containerdummy = createVehicle ["Land_Cargo20_blue_F", [3450.7363, 16708.432, 90], [], 0, "CAN_COLLIDE"];
_containerdummy attachTo [heli1,[0,0,-3.5]];
_containerdummy setDir 90;
while { _dest distance heli1 > 750 } do { "marcador_paquete" setMarkerPos getPos heli1; sleep 1; };
_posairdrop = mapGridPosition _dest;
_txtf = format ["Los Radares de Metropolis han alertado sobre un contenedor sospechoso arrojado en coordenadas %1",_posairdrop];
[[10, "Aviso", [1,0,0], 1.5, _txtf, [1,1,1], 1], "ica_fnc_anuncio", WEST, false, false] call life_fnc_MP;
deleteVehicle _containerdummy;
sleep 0.1;
_container = createVehicle ["Land_Cargo20_blue_F", [3450.7363, 16708.432, 90], [], 0, "CAN_COLLIDE"];
_para = createVehicle ["O_Parachute_02_F", [getPos heli1 select 0, getPos heli1 select 1, getPos heli1 select 2], [], 0, ""];
_para setPosATL (heli1 modelToWorld[0,0,100]);
_para attachTo [heli1,[0,0,-10]];
detach _para;
_container attachTo [_para,[0,0,-2]];
_container setDir 90;
playSound3D ["a3\sounds_f\weapons\Flare_Gun\flaregun_1_shoot.wss", _container];
_smoke="SmokeShellGreen" createVehicle [getpos _container select 0, getpos _container select 1,0];
_smoke attachTo [_container,[0,0,0]];
_light = "Chemlight_green" createVehicle getPos _container;
_light attachTo [_container,[0,0,0]];
_flare = "F_40mm_Green" createVehicle getPos _container;
_flare attachTo [_container,[0,0,0]];
sleep 0.1;
while { (getPos _container select 2) > 2 } do { "marcador_paquete" setMarkerPos getPos _container;sleep 1; };
detach _container;
_container setPos [getPos _container select 0, getPos _container select 1, (getPos _container select 2)+0.5];
playSound3D ["A3\Sounds_F\sfx\alarm_independent.wss", _container];
sleep 6;
"M_NLAW_AT_F" createVehicle [getPos _container select 0, getPos _container select 1, 0];
_pos_container = getPos _container;
deleteVehicle _container;
sleep 0.5;
_box = createVehicle ["CargoNet_01_box_F", _pos_container, [], 0, "CAN_COLLIDE"];
_box allowDamage false;
_smoke="SmokeShellGreen" createVehicle [getpos _box select 0,getpos _box select 1,0];
_flare = "F_40mm_Green" createVehicle getPos _container;
_light attachTo [_box,[0,0,0]];
_flare attachTo [_box,[0,0,0]];
clearWeaponCargoGlobal _box;
clearMagazineCargoGlobal _box;
clearItemCargoGlobal _box;
_varcargo=floor(random 2);
if (_varcargo==1) then {
_box addWeaponCargoGlobal ["CUP_srifle_AWM_des", 1];
_box addItemCargoGlobal ["CUP_muzzle_snds_AWM", 1];
_box addItemCargoGlobal ["CUP_5Rnd_86x70_L115A1", 10];
_box addItemCargoGlobal ["optic_KHS_tan", 1];
_box addItemCargoGlobal ["CUP_bipod_Harris_1A2_L", 1];
};
if (_varcargo==2) then {
_box addWeaponCargoGlobal ["CUP_launch_RPG7V", 1];
_box addItemCargoGlobal ["CUP_PG7V_M", 1];
};
sleep 30;
deleteVehicle heli1;
sleep 120;
deleteVehicle _box; 
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)-21,(getPos _box select 1)+21,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)-1,(getPos _box select 1)+56,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)+23,(getPos _box select 1)-75,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)-50,(getPos _box select 1)+1,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)+87,(getPos _box select 1)-22,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)+0,(getPos _box select 1)-0,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)+20,(getPos _box select 1)-20,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)-100,(getPos _box select 1)+56,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)+100,(getPos _box select 1)-100,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)-55,(getPos _box select 1)+123,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)+577,(getPos _box select 1)-83,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)+35,(getPos _box select 1)-99,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)+100,(getPos _box select 1)-100,0];
sleep 1;
_bmb = "BO_GBU12_LGB" createVehicle [(getPos _box select 0)-431,(getPos _box select 1)-431,0];
"Markerpaquetetext" setMarkerAlpha 0;
deleteMarker "marcador_paquete";
deleteMarker "Markerpaquetetext";
paqueteaereo_goingon = false;